// 根项目构建配置

import java.io.File
import java.util.Properties

/**
 * 自动检测并设置 Android SDK 路径
 * 支持 Windows 和 macOS 系统
 */
tasks.register("setupLocalProperties") {
    group = "setup"
    description = "自动检测操作系统并设置 Android SDK 路径到 local.properties"
    
    doLast {
        val localPropertiesFile = File(rootProject.projectDir, "local.properties")
        
        // 检测操作系统
        val osName = System.getProperty("os.name").lowercase()
        val isWindows = osName.contains("windows")
        val isMac = osName.contains("mac") || osName.contains("darwin")
        
        // 根据操作系统设置默认 SDK 路径
        val sdkPath = when {
            isWindows -> {
                // Windows 系统：尝试多个可能的路径
                val userName = System.getProperty("user.name")
                val userHome = System.getProperty("user.home")
                val possiblePaths = listOf(
                    System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT"),
                    "$userHome\\AppData\\Local\\Android\\Sdk",
                    "C:\\Users\\$userName\\AppData\\Local\\Android\\Sdk",
                    "$userHome\\AppData\\Local\\Android\\Sdk"
                )
                
                possiblePaths.firstOrNull { path ->
                    path != null && File(path).exists()
                } ?: "C:\\Users\\$userName\\AppData\\Local\\Android\\Sdk"
            }
            isMac -> {
                // macOS 系统：尝试多个可能的路径
                val userName = System.getProperty("user.name")
                val userHome = System.getProperty("user.home")
                val possiblePaths = listOf(
                    System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT"),
                    "$userHome/Library/Android/sdk",
                    "/Users/$userName/Library/Android/sdk",
                    "$userHome/Library/Android/sdk"
                )
                
                possiblePaths.firstOrNull { path ->
                    path != null && File(path).exists()
                } ?: "/Users/$userName/Library/Android/sdk"
            }
            else -> {
                // Linux 或其他系统
                System.getenv("ANDROID_HOME") 
                    ?: System.getenv("ANDROID_SDK_ROOT")
                    ?: System.getProperty("user.home") + "/Android/Sdk"
            }
        }
        
        // 读取现有的 local.properties 文件
        val props = Properties()
        if (localPropertiesFile.exists()) {
            localPropertiesFile.inputStream().use { props.load(it) }
        }
        
        // 检查路径是否需要更新
        val currentSdkPath = props.getProperty("sdk.dir")
        val normalizedCurrentPath = currentSdkPath?.replace("\\", File.separator)?.replace("/", File.separator)
        val normalizedSdkPath = sdkPath.replace("\\", File.separator).replace("/", File.separator)
        
        // 如果路径不同或文件不存在，则更新
        if (normalizedCurrentPath != normalizedSdkPath || !localPropertiesFile.exists()) {
            // 转换路径格式
            val formattedPath = if (isWindows) {
                // Windows: 使用正斜杠，Gradle 和 Android Studio 都支持
                // 例如：C:/Users/username/AppData/Local/Android/Sdk
                sdkPath.replace("\\", "/")
            } else {
                sdkPath
            }
            
            // 手动写入文件，避免 Properties.store() 的转义问题
            localPropertiesFile.writer().use { writer ->
                writer.write("## This file must *NOT* be checked into Version Control Systems,\n")
                writer.write("# as it contains information specific to your local configuration.\n")
                writer.write("#\n")
                writer.write("# Location of the SDK. This is only used by Gradle.\n")
                writer.write("# For customization when using a Version Control System, please read the\n")
                writer.write("# header note.\n")
                writer.write("# This file is auto-generated by the setupLocalProperties task.\n")
                writer.write("sdk.dir=$formattedPath\n")
            }
            
            println("✓ 已更新 local.properties，SDK 路径设置为: $formattedPath")
        } else {
            println("✓ local.properties 已存在且路径正确，无需更新")
            println("  当前 SDK 路径: $normalizedCurrentPath")
        }
        
        // 验证路径是否存在
        val sdkFile = File(sdkPath)
        if (!sdkFile.exists()) {
            println("⚠ 警告: SDK 路径不存在: $sdkPath")
            println("  请确保已安装 Android SDK 或设置 ANDROID_HOME 环境变量")
        } else {
            println("✓ SDK 路径验证成功: $sdkPath")
        }
    }
}

// 在执行任何构建任务之前，自动运行 setupLocalProperties（仅在需要时）
tasks.whenTaskAdded {
    if (this.name == "preBuild" || this.name == "prepareKotlinBuildScriptModel") {
        val setupTask = rootProject.tasks.findByName("setupLocalProperties")
        if (setupTask != null) {
            this.dependsOn(setupTask)
        }
    }
}